[project]
name = "weightedgraphs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vegard Pareli Seines", email = "vegsei@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
]

[project.scripts]
weightedgraphs = "weightedgraphs:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
